name: Build Lizzie (Windows)

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 8 (Temurin)
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '8'
        cache: maven

    - name: Build with Maven
      run: mvn -B -DskipTests package

    - name: Upload shaded JAR artifact
      uses: actions/upload-artifact@v4
      with:
        name: lizzie-jar
        path: |
          target/*-shaded.jar
          target/*.jar
        if-no-files-found: error
        retention-days: 7
